name: CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.MD"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.MD"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: sa-cluster
  ECR_REPOSITORY: simple-app
  NAMESPACE: simple-app-ns

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Login Amazon to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"

      - name: Build and Push to ECR Registry
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # using commit SHA since we won't have releases
          # We'll tag it as "latest" so it won't affect anything or cause any trouble
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 

          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \ 
                     $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Run Snyk to check Docker images for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ steps.login-ecr.outputs.registry }}/simple-app:${{ github.sha }}
          args: --severity-threshold=high

  deploy-to-eks:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }}

      - name: Deploy to k8s
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" simple-app/templates/deployment.yaml
          kubectl get ns $NAMESPACE || kubectl create ns $NAMESPACE
          helm upgrade --install simple-app ./simple-app --namespace $NAMESPACE --set image.tag=$IMAGE_TAG
          kubectl rollout status deployment/$ECR_REPOSITORY -n $NAMESPACE

  summary-notif:
    needs: [build-and-push, deploy-to-eks]
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notify
        if: Always()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          STATUS=${{ job.status }}
          COLOR=$([[ "$STATUS" == "success" ]] && echo "3066993" || echo "15158332")
              curl -X POST "$DISCORD_WEBHOOK_URL" \
                -H "Content-Type: application/json" \
                -d '{
                  "embeds": [{
                    "title": "CD Pipeline — '"$STATUS"'",
                    "color": '"$COLOR"',
                    "fields": [
                      { "name": "Repo", "value": "${{ github.repository }}", "inline": true },
                      { "name": "Branch", "value": "${{ github.ref_name }}", "inline": true },
                      { "name": "Image Tag", "value": "${{ github.sha }}", "inline": false },
                      { "name": "Environment", "value": "EKS", "inline": true }
                    ]
                  }]
                }'
