name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          echo "Installing Dependencies..."
          pip install -r app/requirements.txt
          pip install black flake8 mypy bandit pip-audit
          echo "Done"

      - name: Lint The Code
        run: |
          black --check .
          mypy .
          flake8 .

      - name: Security Scan
        run: |
          echo "Running Security Scan..."
          bandit -r app 
          pip-audit
          echo "Done"

      - name: Run Tests
        run: |
          echo "Running tests..."
          pytest app/tests/
          echo "Done"

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Scan Dependencies
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Scan Iac
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
